language: python
python:
- 2.7

services:
- docker

install:
- docker build -t mheene/docker-afd .
- docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --name afd --mount source=afd_work_dir,target=/home/afd/local --mount source=data,target=/home/afd/data mheene/docker-afd


script: docker ps | grep -q afd
