version: '3'
services:
  afd:
    image: "mheene/docker-afd"
    volumes:
      - /tmp:/home/afd/data
    command: ["date"]
     
  apache:
    depends_on:
     - afd
    image: "httpd"
    ports:
     - "8123:80"
    volumes:
     - /tmp:/usr/local/apache2/htdocs/

     